#include "scion/integration/GaussLegendre/2.hpp"
#include "scion/integration/GaussLegendre/4.hpp"
#include "scion/integration/GaussLegendre/6.hpp"
#include "scion/integration/GaussLegendre/7.hpp"
#include "scion/integration/GaussLegendre/8.hpp"
#include "scion/integration/GaussLegendre/10.hpp"
