// integration objects and functions
#include "scion/integration/Histogram.hpp"
#include "scion/integration/HistogramMean.hpp"
#include "scion/integration/HistogramVariance.hpp"
#include "scion/integration/LinearLinear.hpp"
#include "scion/integration/LinearLinearMean.hpp"
#include "scion/integration/LinearLogarithmic.hpp"
#include "scion/integration/LogarithmicLinear.hpp"
#include "scion/integration/LogarithmicLogarithmic.hpp"
#include "scion/integration/GaussLegendre.hpp"
#include "scion/integration/GaussLobatto.hpp"
