#######################################################################
# Setup
#######################################################################

enable_testing()

FetchContent_MakeAvailable( Catch2 )

function( add_cpp_test name source )

  set( test_name "scion.${name}.test" )
  add_executable( ${test_name} ${source} )
  add_test( NAME ${test_name} COMMAND ${test_name} )
  set_target_properties( ${test_name} PROPERTIES COMPILE_DEFINITIONS "PYBIND11" )
  target_link_libraries( ${test_name} PRIVATE scion )
  target_link_libraries( ${test_name} PRIVATE Catch2::Catch2WithMain )

  file( GLOB resources "resources/*" )
  foreach( resource ${resources} )
    file( COPY "${resource}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}" )
  endforeach()

endfunction()

#######################################################################
# Unit testing directories
#######################################################################

message( STATUS "Adding scion C++ unit testing" )

add_cpp_test( scion.integration.GaussLegendre.10  scion/integration/GaussLegendre/10.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.16  scion/integration/GaussLegendre/16.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.2  scion/integration/GaussLegendre/2.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.32  scion/integration/GaussLegendre/32.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.4  scion/integration/GaussLegendre/4.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.6  scion/integration/GaussLegendre/6.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.64  scion/integration/GaussLegendre/64.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.7  scion/integration/GaussLegendre/7.test.cpp )
add_cpp_test( scion.integration.GaussLegendre.8  scion/integration/GaussLegendre/8.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.10  scion/integration/GaussLobatto/10.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.16  scion/integration/GaussLobatto/16.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.2  scion/integration/GaussLobatto/2.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.32  scion/integration/GaussLobatto/32.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.4  scion/integration/GaussLobatto/4.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.6  scion/integration/GaussLobatto/6.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.64  scion/integration/GaussLobatto/64.test.cpp )
add_cpp_test( scion.integration.GaussLobatto.8  scion/integration/GaussLobatto/8.test.cpp )
add_cpp_test( scion.integration.Histogram  scion/integration/Histogram.test.cpp )
add_cpp_test( scion.integration.HistogramMean  scion/integration/HistogramMean.test.cpp )
add_cpp_test( scion.integration.HistogramVariance  scion/integration/HistogramVariance.test.cpp )
add_cpp_test( scion.integration.LinearLinear  scion/integration/LinearLinear.test.cpp )
add_cpp_test( scion.integration.LinearLinearMean  scion/integration/LinearLinearMean.test.cpp )
add_cpp_test( scion.integration.LinearLinearVariance  scion/integration/LinearLinearVariance.test.cpp )
add_cpp_test( scion.integration.LinearLogarithmic  scion/integration/LinearLogarithmic.test.cpp )
add_cpp_test( scion.integration.LinearLogarithmicMean  scion/integration/LinearLogarithmicMean.test.cpp )
add_cpp_test( scion.integration.LogarithmicLinear  scion/integration/LogarithmicLinear.test.cpp )
add_cpp_test( scion.integration.LogarithmicLinearMean  scion/integration/LogarithmicLinearMean.test.cpp )
add_cpp_test( scion.integration.LogarithmicLogarithmic  scion/integration/LogarithmicLogarithmic.test.cpp )
add_cpp_test( scion.integration.LogarithmicLogarithmicMean  scion/integration/LogarithmicLogarithmicMean.test.cpp )
add_cpp_test( scion.integration.cumulativeIntegral  scion/integration/cumulativeIntegral.test.cpp )
add_cpp_test( scion.integration.integral  scion/integration/integral.test.cpp )
add_cpp_test( scion.interpolation.Histogram  scion/interpolation/Histogram.test.cpp )
add_cpp_test( scion.interpolation.LinearLinear  scion/interpolation/LinearLinear.test.cpp )
add_cpp_test( scion.interpolation.LinearLogarithmic  scion/interpolation/LinearLogarithmic.test.cpp )
add_cpp_test( scion.interpolation.LogarithmicLinear  scion/interpolation/LogarithmicLinear.test.cpp )
add_cpp_test( scion.interpolation.LogarithmicLogarithmic  scion/interpolation/LogarithmicLogarithmic.test.cpp )
add_cpp_test( scion.linearisation.Lineariser  scion/linearisation/Lineariser.test.cpp )
add_cpp_test( scion.linearisation.MidpointSplit  scion/linearisation/MidpointSplit.test.cpp )
add_cpp_test( scion.linearisation.ToleranceConvergence  scion/linearisation/ToleranceConvergence.test.cpp )
add_cpp_test( scion.math.AnalyticalIntegrator  scion/math/AnalyticalIntegrator.test.cpp )
add_cpp_test( scion.math.ChebyshevApproximation  scion/math/ChebyshevApproximation.test.cpp )
add_cpp_test( scion.math.ChebyshevSeries  scion/math/ChebyshevSeries.test.cpp )
add_cpp_test( scion.math.HistogramTable  scion/math/HistogramTable.test.cpp )
add_cpp_test( scion.math.HistogramTableFunction  scion/math/HistogramTableFunction.test.cpp )
add_cpp_test( scion.math.InterpolationTable  scion/math/InterpolationTable.test.cpp )
add_cpp_test( scion.math.InterpolationTableFunction  scion/math/InterpolationTableFunction.test.cpp )
add_cpp_test( scion.math.IntervalDomain  scion/math/IntervalDomain.test.cpp )
add_cpp_test( scion.math.LegendreSeries  scion/math/LegendreSeries.test.cpp )
add_cpp_test( scion.math.LinearLinearTable  scion/math/LinearLinearTable.test.cpp )
add_cpp_test( scion.math.LinearLinearTableFunction  scion/math/LinearLinearTableFunction.test.cpp )
add_cpp_test( scion.math.LinearLogTable  scion/math/LinearLogTable.test.cpp )
add_cpp_test( scion.math.LinearLogTableFunction  scion/math/LinearLogTableFunction.test.cpp )
add_cpp_test( scion.math.LogLinearTable  scion/math/LogLinearTable.test.cpp )
add_cpp_test( scion.math.LogLinearTableFunction  scion/math/LogLinearTableFunction.test.cpp )
add_cpp_test( scion.math.LogLogTable  scion/math/LogLogTable.test.cpp )
add_cpp_test( scion.math.LogLogTableFunction  scion/math/LogLogTableFunction.test.cpp )
add_cpp_test( scion.math.OpenDomain  scion/math/OpenDomain.test.cpp )
add_cpp_test( scion.math.PolynomialSeries  scion/math/PolynomialSeries.test.cpp )
add_cpp_test( scion.math.chebyshev  scion/math/chebyshev.test.cpp )
add_cpp_test( scion.math.clenshaw  scion/math/clenshaw.test.cpp )
add_cpp_test( scion.math.compare  scion/math/compare.test.cpp )
add_cpp_test( scion.math.horner  scion/math/horner.test.cpp )
add_cpp_test( scion.math.legendre  scion/math/legendre.test.cpp )
add_cpp_test( scion.math.newton  scion/math/newton.test.cpp )
add_cpp_test( scion.unionisation.Unioniser  scion/unionisation/Unioniser.test.cpp )
add_cpp_test( scion.verification.ranges  scion/verification/ranges.test.cpp )
add_cpp_test( utility.IteratorView  utility/IteratorView.test.cpp )
