#######################################################################
# Setup
#######################################################################

enable_testing()

FetchContent_MakeAvailable( Catch2 )

function( add_cpp_test name source )

  set( test_name "scion.${name}.test" )
  add_executable( ${test_name} ${source} )
  add_test( NAME ${test_name} COMMAND ${test_name} )
  set_target_properties( ${test_name} PROPERTIES COMPILE_DEFINITIONS "PYBIND11" )
  target_link_libraries( ${test_name} PRIVATE scion )
  target_link_libraries( ${test_name} PRIVATE Catch2::Catch2WithMain )

  file( GLOB resources "resources/*" )
  foreach( resource ${resources} )
    file( COPY "${resource}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}" )
  endforeach()

endfunction()

#######################################################################
# Unit testing directories
#######################################################################

message( STATUS "Adding scion C++ unit testing" )

add_cpp_test( scion.integration.GaussLegendre.10  scion/integration/GaussLegendre/10 )
add_cpp_test( scion.integration.GaussLegendre.16  scion/integration/GaussLegendre/16 )
add_cpp_test( scion.integration.GaussLegendre.2  scion/integration/GaussLegendre/2 )
add_cpp_test( scion.integration.GaussLegendre.32  scion/integration/GaussLegendre/32 )
add_cpp_test( scion.integration.GaussLegendre.4  scion/integration/GaussLegendre/4 )
add_cpp_test( scion.integration.GaussLegendre.6  scion/integration/GaussLegendre/6 )
add_cpp_test( scion.integration.GaussLegendre.64  scion/integration/GaussLegendre/64 )
add_cpp_test( scion.integration.GaussLegendre.7  scion/integration/GaussLegendre/7 )
add_cpp_test( scion.integration.GaussLegendre.8  scion/integration/GaussLegendre/8 )
add_cpp_test( scion.integration.GaussLobatto.10  scion/integration/GaussLobatto/10 )
add_cpp_test( scion.integration.GaussLobatto.16  scion/integration/GaussLobatto/16 )
add_cpp_test( scion.integration.GaussLobatto.2  scion/integration/GaussLobatto/2 )
add_cpp_test( scion.integration.GaussLobatto.32  scion/integration/GaussLobatto/32 )
add_cpp_test( scion.integration.GaussLobatto.4  scion/integration/GaussLobatto/4 )
add_cpp_test( scion.integration.GaussLobatto.6  scion/integration/GaussLobatto/6 )
add_cpp_test( scion.integration.GaussLobatto.64  scion/integration/GaussLobatto/64 )
add_cpp_test( scion.integration.GaussLobatto.8  scion/integration/GaussLobatto/8 )
add_cpp_test( scion.integration.Histogram  scion/integration/Histogram )
add_cpp_test( scion.integration.HistogramMean  scion/integration/HistogramMean )
add_cpp_test( scion.integration.HistogramVariance  scion/integration/HistogramVariance )
add_cpp_test( scion.integration.LinearLinear  scion/integration/LinearLinear )
add_cpp_test( scion.integration.LinearLinearMean  scion/integration/LinearLinearMean )
add_cpp_test( scion.integration.LinearLinearVariance  scion/integration/LinearLinearVariance )
add_cpp_test( scion.integration.LinearLogarithmic  scion/integration/LinearLogarithmic )
add_cpp_test( scion.integration.LinearLogarithmicMean  scion/integration/LinearLogarithmicMean )
add_cpp_test( scion.integration.LogarithmicLinear  scion/integration/LogarithmicLinear )
add_cpp_test( scion.integration.LogarithmicLinearMean  scion/integration/LogarithmicLinearMean )
add_cpp_test( scion.integration.LogarithmicLogarithmic  scion/integration/LogarithmicLogarithmic )
add_cpp_test( scion.integration.LogarithmicLogarithmicMean  scion/integration/LogarithmicLogarithmicMean )
add_cpp_test( scion.integration.cumulativeIntegral  scion/integration/cumulativeIntegral )
add_cpp_test( scion.integration.integral  scion/integration/integral )
add_cpp_test( scion.interpolation.Histogram  scion/interpolation/Histogram )
add_cpp_test( scion.interpolation.LinearLinear  scion/interpolation/LinearLinear )
add_cpp_test( scion.interpolation.LinearLogarithmic  scion/interpolation/LinearLogarithmic )
add_cpp_test( scion.interpolation.LogarithmicLinear  scion/interpolation/LogarithmicLinear )
add_cpp_test( scion.interpolation.LogarithmicLogarithmic  scion/interpolation/LogarithmicLogarithmic )
add_cpp_test( scion.linearisation.Lineariser  scion/linearisation/Lineariser )
add_cpp_test( scion.linearisation.MidpointSplit  scion/linearisation/MidpointSplit )
add_cpp_test( scion.linearisation.ToleranceConvergence  scion/linearisation/ToleranceConvergence )
add_cpp_test( scion.math.AnalyticalIntegrator  scion/math/AnalyticalIntegrator )
add_cpp_test( scion.math.ChebyshevApproximation  scion/math/ChebyshevApproximation )
add_cpp_test( scion.math.ChebyshevSeries  scion/math/ChebyshevSeries )
add_cpp_test( scion.math.HistogramTable  scion/math/HistogramTable )
add_cpp_test( scion.math.HistogramTableFunction  scion/math/HistogramTableFunction )
add_cpp_test( scion.math.InterpolationTable  scion/math/InterpolationTable )
add_cpp_test( scion.math.InterpolationTableFunction  scion/math/InterpolationTableFunction )
add_cpp_test( scion.math.IntervalDomain  scion/math/IntervalDomain )
add_cpp_test( scion.math.LegendreSeries  scion/math/LegendreSeries )
add_cpp_test( scion.math.LinearLinearTable  scion/math/LinearLinearTable )
add_cpp_test( scion.math.LinearLinearTableFunction  scion/math/LinearLinearTableFunction )
add_cpp_test( scion.math.LinearLogTable  scion/math/LinearLogTable )
add_cpp_test( scion.math.LinearLogTableFunction  scion/math/LinearLogTableFunction )
add_cpp_test( scion.math.LogLinearTable  scion/math/LogLinearTable )
add_cpp_test( scion.math.LogLinearTableFunction  scion/math/LogLinearTableFunction )
add_cpp_test( scion.math.LogLogTable  scion/math/LogLogTable )
add_cpp_test( scion.math.LogLogTableFunction  scion/math/LogLogTableFunction )
add_cpp_test( scion.math.OpenDomain  scion/math/OpenDomain )
add_cpp_test( scion.math.PolynomialSeries  scion/math/PolynomialSeries )
add_cpp_test( scion.math.chebyshev  scion/math/chebyshev )
add_cpp_test( scion.math.clenshaw  scion/math/clenshaw )
add_cpp_test( scion.math.compare  scion/math/compare )
add_cpp_test( scion.math.horner  scion/math/horner )
add_cpp_test( scion.math.legendre  scion/math/legendre )
add_cpp_test( scion.math.newton  scion/math/newton )
add_cpp_test( scion.unionisation.Unioniser  scion/unionisation/Unioniser )
add_cpp_test( scion.verification.ranges  scion/verification/ranges )
add_cpp_test( utility.IteratorView  utility/IteratorView )

